pages: []
docs:
  - from: packages/tdev/material-sync/README.mdx
    to: tdev-website/docs/intro/03-class-management/index.mdx
29Fa:
  - from: docs/01-Algorithmik/
    as: 01-Algorithmik
    ignore: []
  - from: docs/02-Programmieren-OFI/
    as: 02-Programmieren
    ignore: []
30Gb:
  - from: docs/01-Algorithmik/
    as: 01-Algorithmik
    ignore: []
30Ge:
  - from: docs/01-Algorithmik/
    as: 01-Algorithmik
    ignore: []
30Gd:
  - from: docs/01-Algorithmik/
    as: 01-Algorithmik
    ignore: []
